# Generated by Django 4.0.3 on 2022-03-12 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndicadoresModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_semana', models.IntegerField()),
                ('razon_social', models.CharField(max_length=50)),
                ('monto', models.IntegerField()),
            ],
        ),
    ]
