# Generated by Django 4.0.3 on 2022-03-19 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IndicadoresDinero', '0002_indicadoresmodel_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicadoresmodel',
            name='tipo',
            field=models.CharField(default='', max_length=50),
        ),
    ]
