# Generated by Django 4.0.3 on 2022-03-24 04:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IndicadoresDinero', '0003_indicadoresmodel_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicadoresmodel',
            name='num_semana',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
