# Generated by Django 4.0.3 on 2022-03-25 18:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IndicadoresDinero', '0004_alter_indicadoresmodel_num_semana'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicadoresmodel',
            name='monto',
        ),
        migrations.RemoveField(
            model_name='indicadoresmodel',
            name='num_semana',
        ),
        migrations.AddField(
            model_name='indicadoresmodel',
            name='semana1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AddField(
            model_name='indicadoresmodel',
            name='semana2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AddField(
            model_name='indicadoresmodel',
            name='semana3',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AddField(
            model_name='indicadoresmodel',
            name='semana4',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AddField(
            model_name='indicadoresmodel',
            name='semana5',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
