# Generated by Django 4.0.3 on 2022-03-25 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IndicadoresDinero', '0005_remove_indicadoresmodel_monto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indicadoresmodel',
            old_name='fecha',
            new_name='mes',
        ),
    ]
