# Generated by Django 4.0.3 on 2022-03-12 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriasModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clasificacion', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('sub_categoria', models.CharField(max_length=50)),
            ],
        ),
    ]
