# Generated by Django 4.0.3 on 2022-03-15 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Categorias', '0001_initial'),
        ('FlujoEfectivo', '0002_flujomodel_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flujomodel',
            name='id_categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Categorias.categoriasmodel'),
        ),
    ]
