# Generated by Django 4.0.3 on 2022-03-19 03:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlujoEfectivo', '0003_alter_flujomodel_id_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flujomodel',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
